@startuml
left to right direction
actor "Admin Cabang" as AdminCabang

package "Manajemen Akun & Dashboard" {
  AdminCabang --|> (Login Admin Cabang)
  AdminCabang --|> (Kelola Profil Admin Cabang)
  note right of (Kelola Profil Admin Cabang)
    Mengubah nama, email, password diri sendiri.
  end note
  AdminCabang --|> (Lihat Dashboard & Statistik Cabang)
}

package "Manajemen Operasional Cabang" {
  AdminCabang --|> (Kelola Informasi Cabang Sendiri)
  note right of (Kelola Informasi Cabang Sendiri)
    Mengubah gambar, nama, alamat, dll.
    untuk cabang yang dikelola.
  end note

  AdminCabang --|> (Kelola Staff Admin untuk Cabang)

  AdminCabang --|> (Kelola OTA Bekerjasama dengan Cabang)
  (Kelola OTA Bekerjasama dengan Cabang) ..> (Aktifkan OTA untuk Cabang) : <<include>>
  (Kelola OTA Bekerjasama dengan Cabang) ..> (Nonaktifkan OTA untuk Cabang) : <<include>>

  AdminCabang --|> (Kelola Jenis Pod Cabang CRUD)
  AdminCabang --|> (Kelola Pod Cabang CRUD)
  (Kelola Pod Cabang CRUD) ..> (Monitor Status Pod) : <<include>>
  (Kelola Pod Cabang CRUD) ..> (Ubah Status Pod Maintenance, dll) : <<include>>

  AdminCabang --|> (Kelola Voucher Khusus Cabang CRUD)
  AdminCabang --|> (Kelola Pengaturan Harga Dinamis Pod CRUD)
  note bottom of (Kelola Pengaturan Harga Dinamis Pod CRUD)
    Untuk jenis pod pada cabang
    dengan rentang waktu tertentu.
  end note
}
@enduml
