@startuml
left to right direction
actor "Admin Cabang" as AdminCabang

package "Manajemen Akun & Dashboard" {
  AdminCabang --|> (Login Admin Cabang)
  AdminCabang --|> (Kelola Profil Admin Cabang)
  note right of (Kelola Profil Admin Cabang)
    Mengubah nama, email, password diri sendiri.
  end note
  AdminCabang --|> (Lihat Dashboard & Statistik Cabang)
}

package "Manajemen Operasional Cabang" {
  AdminCabang --|> (Kelola Informasi Cabang Sendiri)
  note right of (Kelola Informasi Cabang Sendiri)
    Mengubah gambar, nama, alamat, dll.
    untuk cabang yang dikelola.
  end note

  AdminCabang --|> (Kelola Staff Admin untuk Cabang)
  note right of (Kelola Staff Admin untuk Cabang)
    CRUD admin lain dalam satu cabang.
    (Membutuhkan hak akses dari SuperAdmin).
  end note

  AdminCabang --|> (Kelola OTA Bekerjasama dengan Cabang)
  (Kelola OTA Bekerjasama dengan Cabang) ..> (Aktifkan OTA untuk Cabang) : <<include>>
  (Kelola OTA Bekerjasama dengan Cabang) ..> (Nonaktifkan OTA untuk Cabang) : <<include>>

  AdminCabang --|> (Kelola Jenis Pod Cabang CRUD)
  AdminCabang --|> (Kelola Pod Cabang CRUD)
  (Kelola Pod Cabang CRUD) ..> (Monitor Status Pod) : <<include>>
  (Kelola Pod Cabang CRUD) ..> (Ubah Status Pod Maintenance, dll) : <<include>>

  AdminCabang --|> (Kelola Voucher Khusus Cabang CRUD)
  AdminCabang --|> (Kelola Pengaturan Harga Dinamis Pod CRUD)
  note bottom of (Kelola Pengaturan Harga Dinamis Pod CRUD)
    Untuk jenis pod pada cabang
    dengan rentang waktu tertentu.
  end note
}

package "Manajemen Reservasi & Pengunjung Cabang" {
  AdminCabang --|> (Input Transaksi Reservasi via OTA Manual)
  note bottom of (Input Transaksi Reservasi via OTA Manual)
    Agar dapat disinkronisasi oleh Pengguna.
  end note

  AdminCabang --|> (Pindahkan Pengunjung Check-in ke Pod Lain)
  (Pindahkan Pengunjung Check-in ke Pod Lain) ..> (Pilih Pod Pengganti Tersedia) : <<include>>
  (Pindahkan Pengunjung Check-in ke Pod Lain) ..> (Catat Log Pemindahan Pod) : <<include>>
  AdminCabang --|> (Lihat Catatan Pemindahan Pod)

  AdminCabang --|> (Lakukan Pembersihan Pod)
  (Lakukan Pembersihan Pod) ..> (Update Status Pod menjadi Dibersihkan/Tersedia) : <<include>>
  (Lakukan Pembersihan Pod) ..> (Catat Log Pembersihan) : <<include>>
  AdminCabang --|> (Lihat Catatan Pembersihan Pod)
}

package "Interaksi Pengguna & Review Cabang" {
  AdminCabang --|> (Lihat & Kelola Review Pengguna Cabang)
  (Lihat & Kelola Review Pengguna Cabang) <.. (Setujui Tampilkan Review ke Publik) : <<extend>>
  (Lihat & Kelola Review Pengguna Cabang) <.. (Sembunyikan Review dari Publik) : <<extend>>
}
@enduml